"""Aesthetic integration pipeline for GLDtk.

Builds all Part 4 outputs in one deterministic pass:
1) Theme selection from description keywords
2) Auto-tiling from the IR tile grid
3) Golden-path entity placement
4) AestheticData payload for LDtk serialization
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Optional

from layout.ir import IREntity, IRLevel
from layout.ldtk_adapter import AestheticData
from layout.sugiyama import NodeLayout
from symbolic.schema import AbstractLevelGraph

from .autotile import autotile_level
from .entities import place_entities
from .themes import Theme, detect_theme


@dataclass
class AestheticBuildResult:
    """All outputs produced by the aesthetic pass."""

    theme: Theme
    aesthetic: AestheticData
    placed_entities: list[IREntity]


def build_aesthetic_layer(
    description: str,
    graph: AbstractLevelGraph,
    node_layouts: Dict[str, NodeLayout],
    ir_level: IRLevel,
    theme_override: Optional[str] = None,
    density: float = 1.0,
    seed: int = 42,
    attach_entities: bool = True,
) -> AestheticBuildResult:
    """Build and optionally attach all Part 4 outputs to an IR level.

    Parameters
    ----------
    description : free-text level description used for keyword theme detection.
    graph : abstract graph used for golden-path driven placements.
    node_layouts : mapping from ``sugiyama_layout``.
    ir_level : rasterized level to auto-tile and enrich with entities.
    theme_override : explicit theme identifier (e.g. "dungeon", "forest").
    density : global multiplier for collectible/enemy density.
    seed : deterministic RNG seed for placement decisions.
    attach_entities : append generated entities to ``ir_level.entities``.

    Returns
    -------
    AestheticBuildResult containing theme, serialized aesthetic payload,
    and the list of entities generated by the placement pass.
    """
    theme = detect_theme(description, override=theme_override)
    tile_entries = autotile_level(ir_level, theme)
    entities = place_entities(
        graph=graph,
        node_layouts=node_layouts,
        theme=theme,
        density=density,
        seed=seed,
    )

    if attach_entities:
        ir_level.entities.extend(entities)

    aesthetic = AestheticData(
        tile_entries=tile_entries,
        bg_color=theme.background_color,
        tileset_uid=theme.tileset_uid,
        tileset_rel_path=theme.tileset_rel_path,
        tileset_px_width=theme.tileset_px_width,
        tileset_px_height=theme.tileset_px_height,
    )

    return AestheticBuildResult(
        theme=theme,
        aesthetic=aesthetic,
        placed_entities=entities,
    )
